version: '3'

networks:
  mysql-phpmyadmin:
    driver: bridge

volumes:
  db:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_minimath
      MYSQL_USER: db_minimath
      MYSQL_PASSWORD: db_group5
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8091:80"
    networks:
      - mysql-phpmyadmin

  web:
    build: .
    container_name: web
    volumes:
      - ./web:/var/www/html
    ports:
      - "8080:80"
    networks:
      - mysql-phpmyadmin

